apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-egress-gateway
  labels:
    app: vpn-egress-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-egress-gateway
  template:
    metadata:
      labels:
        app: vpn-egress-gateway
    spec:
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: gateway
          image: "{{ .Values.registry }}/{{ .Values.gateway.image }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: CONFIG_URL
              value: {{ .Values.configURL | quote }}
            - name: CLUSTER_CIDR
              value: {{ .Values.clusterCIDR | quote }}
            - name: GATEWAY_CIDR
              value: {{ .Values.gatewayCIDR | quote }}
            - name: VPN_SERVER_IP
              value: {{ .Values.vpnServerIP | quote }}
            - name: VXLAN_ID
              value: {{ .Values.vxlanID | quote }}
            - name: VXLAN_PORT
              value: {{ .Values.vxlanPort | quote }}
            - name: VXLAN_NET
              value: {{ .Values.vxlanNet | quote }}
            - name: TUN_IF
              value: {{ .Values.tunIf | default "tun0" | quote }}
            - name: VPN_LOG_LEVEL
              value: {{ .Values.vpnLogLevel | default "1" | quote }}
            - name: DATA_CIPHERS
              value: {{ .Values.dataCiphers | default "AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:AES-128-CBC" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-egress-gateway
  labels:
    app: vpn-egress-gateway
spec:
  type: ClusterIP
  selector:
    app: vpn-egress-gateway
  ports:
    - port: {{ .Values.vxlanPort | default 4790 }}
      targetPort: {{ .Values.vxlanPort | default 4790 }}
      protocol: UDP
      name: vxlan
